imports:
    - { resource: role_hierarchy.yml }
security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '%admin_password%'
                        roles: 'ROLE_SUPER_ADMIN'

        legacy_db_provider:
            entity:
                class: AppBundle:Contact
                property: username
        shop_db_provider:
            entity:
                class: AppBundle:Client
                property: username
        admin_db_provider:
            entity:
                class: AppBundle:User
                property: username
    role_hierarchy: %role_hierarchy%
    encoders:
        AppBundle\Entity\Contact: bcrypt
        AppBundle\Entity\Client: bcrypt
        AppBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/(admin|api|crud)
            provider: admin_db_provider
            anonymous: ~
            form_login:
                login_path: admin-login-form
                check_path: admin-login-form
            json_login:
                check_path: /api/login
        shop:
            pattern: ^/([a-z]{2,3}\/(getterms|cart|shop|order|commande|bestellen|ordine|orden)|shop/(login|register|password-request))
            provider: shop_db_provider
            anonymous: ~
            json_login:
                check_path: /shop/login
        main:
            pattern: ^/
            provider: legacy_db_provider
            anonymous: ~
            json_login:
                check_path: /login
            user_checker: AppBundle\Security\UserChecker
            entry_point: AppBundle\Security\EntryPoint
            logout:
                path:   /logout
                invalidate_session: true
                target: /
            access_denied_handler: AppBundle\Security\AccessDeniedHandler

    access_control:
        # Pas de sécurité sur les routes de l'ancien site (redirection)
        - { path: ^/site/, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/password-request, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/pages, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api, role: ROLE_ADMIN}
        - { path: ^/crud, role: ROLE_ADMIN}
        - { path: ^/admin/_trans, role: ROLE_ADMIN}
        - { path: ^/admin#/*, role: ROLE_ADMIN}
